version: '3'
services:
    upload_backend:
        image: slzcc/uploadserver:backend-v1
        ports:
          - 8878:8878
        environment:
          - UPLOAD_FILE_PATH=/storage/
          - NGINX_MIRROR_URL=http://127.0.0.1:8888/
          - NGINX_MIRROR_STORAGE_PATH=firmware
          - REMOVE_SOURCE_FILE_SETUP=False
          - USE_TIEM_SUB_DIRECTORY=True

        volumes:
          - nginx-upload:/tmp/nginx_upload
          - mirror:/storage

    upload_frontend:
        image: slzcc/uploadserver:frontend-v1
        ports:
          - 8888:80
        environment:
          - UPLOAD_BACKEND_ADDRESS=http://127.0.0.1:8878
          - NGINX_MIRROR_HOME=/mirror

        volumes:
          - nginx-upload:/tmp/nginx_upload
          - mirror:/mirror
volumes:
    nginx-upload:
    mirror: